// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiRsIQ-yWodKpzm30m1qLu6jCAHantORU',
    appId: '1:1059830292645:web:487cdc6c66cd5f2eccad4c',
    messagingSenderId: '1059830292645',
    projectId: 'franca-weather-9eb1f',
    authDomain: 'franca-weather-9eb1f.firebaseapp.com',
    storageBucket: 'franca-weather-9eb1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALdU56OBW7jDnOBst0KXbELNmWyHCrVoI',
    appId: '1:1059830292645:android:eb4a86855859013accad4c',
    messagingSenderId: '1059830292645',
    projectId: 'franca-weather-9eb1f',
    storageBucket: 'franca-weather-9eb1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGiI12ih_nxJ_aX8b867eosENohQN2RhM',
    appId: '1:1059830292645:ios:c6b763787d83011eccad4c',
    messagingSenderId: '1059830292645',
    projectId: 'franca-weather-9eb1f',
    storageBucket: 'franca-weather-9eb1f.firebasestorage.app',
    iosBundleId: 'com.example.francaWeather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGiI12ih_nxJ_aX8b867eosENohQN2RhM',
    appId: '1:1059830292645:ios:c6b763787d83011eccad4c',
    messagingSenderId: '1059830292645',
    projectId: 'franca-weather-9eb1f',
    storageBucket: 'franca-weather-9eb1f.firebasestorage.app',
    iosBundleId: 'com.example.francaWeather',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiRsIQ-yWodKpzm30m1qLu6jCAHantORU',
    appId: '1:1059830292645:web:c13418f3b7708caaccad4c',
    messagingSenderId: '1059830292645',
    projectId: 'franca-weather-9eb1f',
    authDomain: 'franca-weather-9eb1f.firebaseapp.com',
    storageBucket: 'franca-weather-9eb1f.firebasestorage.app',
  );

}